Repository khoj-ai/khoj, pull requests merged in 2023-08, with the labels that each got.

#393 Offline chat: Quality and Reliability Improvements
  src/khoj/interface/web/chat.html
  src/khoj/migrations/migrate_offline_model.py
  src/khoj/migrations/migrate_processor_config_openai.py
  src/khoj/migrations/migrate_version.py
  src/khoj/processor/conversation/gpt4all/chat_model.py
  src/khoj/processor/conversation/gpt4all/model_metadata.py
  src/khoj/processor/conversation/gpt4all/utils.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/helpers.py
  src/khoj/utils/cli.py
  src/khoj/utils/state.py
  tests/conftest.py
  tests/test_conversation_utils.py
  tests/test_gpt4all_chat_actors.py
  tests/test_gpt4all_chat_director.py
Labels: fix, upgrade

#425 Explicitly set Khoj to use the default locale of the user
  src/khoj/main.py
Labels: fix

#420 Add support for indexing plaintext files
  src/khoj/configure.py
  src/khoj/interface/web/assets/icons/plaintext.svg
  src/khoj/interface/web/config.html
  src/khoj/interface/web/content_type_input.html
  src/khoj/interface/web/index.html
  src/khoj/processor/plaintext/__init__.py
  src/khoj/processor/plaintext/plaintext_to_jsonl.py
  src/khoj/routers/api.py
  src/khoj/routers/web_client.py
  src/khoj/utils/config.py
  src/khoj/utils/constants.py
  src/khoj/utils/rawconfig.py
  tests/data/config.yml
  tests/test_plaintext_to_jsonl.py
Labels: upgrade, plugin

#469 Filter knowledge base used by chat to respond
  src/khoj/routers/api.py
  src/khoj/search_filter/base_filter.py
  src/khoj/search_filter/date_filter.py
  src/khoj/search_filter/file_filter.py
  src/khoj/search_filter/word_filter.py
  tests/test_date_filter.py
  tests/test_file_filter.py
  tests/test_gpt4all_chat_director.py
  tests/test_openai_chat_director.py
  tests/test_word_filter.py
Labels: upgrade

#457 Move to a push-first model for retrieving embeddings from local files
  src/khoj/configure.py
  src/khoj/main.py
  src/khoj/processor/github/github_to_jsonl.py
  src/khoj/processor/jsonl/jsonl_to_jsonl.py
  src/khoj/processor/markdown/markdown_to_jsonl.py
  src/khoj/processor/notion/notion_to_jsonl.py
  src/khoj/processor/org_mode/org_to_jsonl.py
  src/khoj/processor/org_mode/orgnode.py
  src/khoj/processor/pdf/pdf_to_jsonl.py
  src/khoj/processor/plaintext/plaintext_to_jsonl.py
  src/khoj/processor/text_to_jsonl.py
  src/khoj/routers/api.py
  src/khoj/routers/indexer.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/fs_syncer.py
  tests/conftest.py
  tests/test_client.py
  tests/test_markdown_to_jsonl.py
  tests/test_org_to_jsonl.py
  tests/test_orgnode.py
  tests/test_pdf_to_jsonl.py
  tests/test_plaintext_to_jsonl.py
  tests/test_text_search.py
Labels: upgrade
