Repository khoj-ai/khoj, pull requests merged in 2023-11, with the labels that each got.

#528 [Multi-User Part 7]: Improve Sign-In UX & Rename DB Models for Readability
  src/database/adapters/__init__.py
  src/database/migrations/0010_rename_embeddings_entry_and_more.py
  src/database/models/__init__.py
  src/khoj/interface/web/assets/icons/key.svg
  src/khoj/interface/web/assets/khoj.css
  src/khoj/interface/web/assets/khoj.js
  src/khoj/interface/web/base_config.html
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/config.html
  src/khoj/interface/web/index.html
  src/khoj/interface/web/login.html
  src/khoj/interface/web/utils.html
  src/khoj/processor/github/github_to_entries.py
  src/khoj/processor/markdown/markdown_to_entries.py
  src/khoj/processor/notion/notion_to_entries.py
  src/khoj/processor/org_mode/org_to_entries.py
  src/khoj/processor/pdf/pdf_to_entries.py
  src/khoj/processor/plaintext/plaintext_to_entries.py
  src/khoj/processor/text_to_entries.py
  src/khoj/routers/api.py
  src/khoj/routers/indexer.py
  src/khoj/routers/web_client.py
  src/khoj/search_type/text_search.py
  tests/conftest.py
  tests/test_client.py
  tests/test_markdown_to_jsonl.py
  tests/test_org_to_jsonl.py
  tests/test_pdf_to_jsonl.py
  tests/test_plaintext_to_jsonl.py
  tests/test_text_search.py
Labels: fix, maintain

#532 Improve Theming of Web, Desktop and Obsidian Client App
  docs/chat.md
  pyproject.toml
  src/interface/desktop/about.html
  src/interface/desktop/assets/icons/khoj-logo-sideways-500.png
  src/interface/desktop/assets/khoj.css
  src/interface/desktop/assets/three.min.js
  src/interface/desktop/chat.html
  src/interface/desktop/config.html
  src/interface/desktop/loading-animation.js
  src/interface/desktop/main.js
  src/interface/desktop/preload.js
  src/interface/desktop/renderer.js
  src/interface/desktop/search.html
  src/interface/desktop/splash.html
  src/interface/desktop/utils.js
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/styles.css
  src/khoj/interface/web/assets/icons/khoj-logo-sideways-500.png
  src/khoj/interface/web/assets/khoj.css
  src/khoj/interface/web/assets/khoj.js
  src/khoj/interface/web/assets/utils.js
  src/khoj/interface/web/base_config.html
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/login.html
  src/khoj/interface/web/search.html
  src/khoj/interface/web/utils.html
  src/khoj/main.py
  src/khoj/migrations/migrate_offline_chat_default_model.py
  src/khoj/migrations/migrate_server_pg.py
  src/khoj/processor/conversation/gpt4all/chat_model.py
  src/khoj/processor/conversation/gpt4all/utils.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/web_client.py
  src/khoj/utils/cli.py
  src/khoj/utils/rawconfig.py
  src/khoj/utils/state.py
  tests/conftest.py
  tests/data/config.yml
  tests/helpers.py
  tests/test_gpt4all_chat_actors.py
Labels: maintain, plugin

#537 Create Billing integration. Improve Settings pages on Desktop, Web apps
  docs/github_integration.md
  docs/notion_integration.md
  pyproject.toml
  src/app/settings.py
  src/database/adapters/__init__.py
  src/database/migrations/0012_entry_file_source.py
  src/database/migrations/0013_subscription.py
  src/database/models/__init__.py
  src/interface/desktop/chat.html
  src/interface/desktop/config.html
  src/interface/desktop/main.js
  src/interface/desktop/preload.js
  src/interface/desktop/renderer.js
  src/khoj/configure.py
  src/khoj/interface/web/assets/icons/computer.png
  src/khoj/interface/web/assets/icons/credit-card.png
  src/khoj/interface/web/base_config.html
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/config.html
  src/khoj/interface/web/content_source_computer_input.html
  src/khoj/interface/web/content_source_github_input.html
  src/khoj/interface/web/content_source_notion_input.html
  src/khoj/interface/web/content_type_input.html
  src/khoj/processor/github/github_to_entries.py
  src/khoj/processor/markdown/markdown_to_entries.py
  src/khoj/processor/notion/notion_to_entries.py
  src/khoj/processor/org_mode/org_to_entries.py
  src/khoj/processor/pdf/pdf_to_entries.py
  src/khoj/processor/plaintext/plaintext_to_entries.py
  src/khoj/processor/text_to_entries.py
  src/khoj/routers/api.py
  src/khoj/routers/auth.py
  src/khoj/routers/indexer.py
  src/khoj/routers/subscription.py
  src/khoj/routers/web_client.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/state.py
  tests/conftest.py
  tests/test_helpers.py
  tests/test_text_search.py
Labels: upgrade

#550 Update documentation to reflect new multi-user config scenario
  docs/README.md
  docs/_sidebar.md
  docs/advanced.md
  docs/assets/khoj_chat_on_desktop.png
  docs/assets/khoj_search_on_desktop.png
  docs/chat.md
  docs/desktop.md
  docs/desktop_installation.md
  docs/development.md
  docs/emacs.md
  docs/features.md
  docs/github_integration.md
  docs/index.html
  docs/notion_integration.md
  docs/obsidian.md
  docs/search.md
  docs/setup.md
  docs/telemetry.md
  docs/web.md
  src/interface/emacs/khoj.el
  src/interface/obsidian/src/main.ts
  src/interface/obsidian/src/settings.ts
  src/khoj/interface/web/config.html
  src/khoj/utils/helpers.py
Labels: documentation

#561 Clean Logs, Improve Message Rendering and Make Khoj Trusted Host Configurable
  src/interface/desktop/chat.html
  src/interface/desktop/search.html
  src/khoj/app/settings.py
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/search.html
  src/khoj/main.py
  src/khoj/search_type/image_search.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/rawconfig.py
Labels: maintain

#568 Handle Server Unavailable Error from Khoj.el
  src/interface/emacs/khoj.el
Labels: fix

#551 Delete Conversation History from Web, Desktop, Obsidian Clients
  src/interface/desktop/assets/icons/trash-solid.svg
  src/interface/desktop/chat.html
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/styles.css
  src/khoj/database/adapters/__init__.py
  src/khoj/interface/web/chat.html
  src/khoj/routers/api.py
Labels: upgrade

#566 Speak to Khoj via Desktop, Web or Obsidian Client
  pyproject.toml
  src/interface/desktop/assets/icons/microphone-solid.svg
  src/interface/desktop/assets/icons/stop-solid.svg
  src/interface/desktop/chat.html
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/styles.css
  src/khoj/database/adapters/__init__.py
  src/khoj/database/admin.py
  src/khoj/database/migrations/0021_speechtotextmodeloptions_and_more.py
  src/khoj/database/models/__init__.py
  src/khoj/interface/web/assets/icons/microphone-solid.svg
  src/khoj/interface/web/assets/icons/stop-solid.svg
  src/khoj/interface/web/chat.html
  src/khoj/processor/conversation/offline/__init__.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/offline/utils.py
  src/khoj/processor/conversation/offline/whisper.py
  src/khoj/processor/conversation/openai/whisper.py
  src/khoj/routers/api.py
  src/khoj/routers/helpers.py
  src/khoj/utils/config.py
  src/khoj/utils/initialization.py
  src/khoj/utils/state.py
  tests/test_gpt4all_chat_actors.py
Labels: upgrade

#571 Render Chat Responses as Markdown in Desktop, Obsidian Client
  src/interface/desktop/chat.html
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/styles.css
  src/khoj/interface/web/chat.html
Labels: upgrade, maintain, plugin
