Repository khoj-ai/khoj, pull requests merged in 2023-07, with the labels that each got.

#256 Add additional request headers to improve telemetry
  src/khoj/routers/api.py
  src/khoj/utils/helpers.py
Labels: upgrade

#263 [Fix] Remove the default behavior of using GUI for Khoj
  README.md
  docker-compose.yml
  src/interface/emacs/khoj.el
  src/interface/obsidian/README.md
  src/khoj/configure.py
  src/khoj/interface/desktop/file_browser.py
  src/khoj/interface/desktop/labelled_text_field.py
  src/khoj/interface/desktop/main_window.py
  src/khoj/interface/desktop/system_tray.py
  src/khoj/main.py
  src/khoj/processor/github/github_to_jsonl.py
  src/khoj/utils/cli.py
  tests/test_cli.py
Labels: fix

#268 Add try-except-finally blocks around configure calls in /update
  src/khoj/configure.py
  src/khoj/routers/api.py
Labels: fix

#269 Simplify some common configuration steps
  src/khoj/interface/web/assets/icons/confirm-icon.svg
  src/khoj/interface/web/base_config.html
  src/khoj/interface/web/config.html
  src/khoj/interface/web/content_type_github_input.html
  src/khoj/interface/web/content_type_input.html
  src/khoj/interface/web/processor_conversation_input.html
  src/khoj/routers/api.py
  src/khoj/routers/web_client.py
Labels: upgrade

#273 Fix misc. first run errors
  src/khoj/configure.py
  src/khoj/interface/web/config.html
Labels: fix

#274 Skip indexing a PDF that has a loading error
  src/khoj/processor/pdf/pdf_to_jsonl.py
Labels: upgrade

#278 ⚡️ Add chat streaming to OpenAI responses
  src/interface/obsidian/package.json
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/yarn.lock
  src/khoj/configure.py
  src/khoj/interface/web/chat.html
  src/khoj/processor/conversation/gpt.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api.py
  src/khoj/utils/helpers.py
Labels: upgrade

#279 Re-instate the scheduler for the demo instances
  src/khoj/configure.py
  src/khoj/main.py
  src/khoj/routers/api.py
Labels: fix

#283 Move remaining chat actors to use OpenAI chat models
  src/khoj/configure.py
  src/khoj/interface/web/processor_conversation_input.html
  src/khoj/processor/conversation/gpt.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api.py
  src/khoj/routers/api_beta.py
  src/khoj/search_filter/date_filter.py
  src/khoj/utils/config.py
  tests/test_chat_actors.py
Labels: upgrade

#287 Make streaming optional for the /chat endpoint
  src/interface/emacs/khoj.el
  src/interface/obsidian/src/chat_modal.ts
  src/khoj/interface/web/chat.html
  src/khoj/routers/api.py
  src/khoj/routers/helpers.py
  tests/test_chat_actors.py
  tests/test_chat_director.py
Labels: fix, upgrade

#284 Add a plugin which allows users to index their Notion pages
  src/khoj/configure.py
  src/khoj/interface/web/assets/icons/notion.svg
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/config.html
  src/khoj/interface/web/content_type_notion_input.html
  src/khoj/interface/web/index.html
  src/khoj/processor/conversation/gpt.py
  src/khoj/processor/notion/notion_to_jsonl.py
  src/khoj/processor/text_to_jsonl.py
  src/khoj/routers/api.py
  src/khoj/routers/web_client.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/config.py
  src/khoj/utils/constants.py
  src/khoj/utils/rawconfig.py
Labels: plugin

#293 [Fix] Obsidian interface setup without PDFs in vault
  src/interface/obsidian/src/utils.ts
Labels: fix

#317 Reuse Search Models across Content Types to reduce Memory Consumption
  src/khoj/configure.py
  src/khoj/routers/api.py
  src/khoj/search_type/image_search.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/config.py
  src/khoj/utils/helpers.py
  src/khoj/utils/rawconfig.py
  src/khoj/utils/state.py
  tests/conftest.py
  tests/test_client.py
  tests/test_image_search.py
  tests/test_text_search.py
Labels: maintain

#325 Stabilize and Simplify Content Indexing
  src/khoj/configure.py
  src/khoj/main.py
  src/khoj/processor/github/github_to_jsonl.py
  src/khoj/processor/jsonl/jsonl_to_jsonl.py
  src/khoj/processor/markdown/markdown_to_jsonl.py
  src/khoj/processor/notion/notion_to_jsonl.py
  src/khoj/processor/org_mode/org_to_jsonl.py
  src/khoj/processor/pdf/pdf_to_jsonl.py
  src/khoj/processor/text_to_jsonl.py
  src/khoj/routers/api.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/jsonl.py
  src/khoj/utils/state.py
  tests/conftest.py
  tests/test_text_search.py
Labels: fix

#333 📝 Add a documentation base for Khoj!
  docs/.nojekyll
  docs/README.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/advanced.md
  docs/assets/favicon-128x128.ico
  docs/assets/interfaces.png
  docs/assets/khoj-logo-sideways-200.png
  docs/assets/khoj-logo-sideways.svg
  docs/assets/khoj_architecture.png
  docs/assets/khoj_chat_on_emacs_0.5.0.png
  docs/assets/khoj_chat_on_obsidian_0.6.0.png
  docs/assets/khoj_chat_web_interface.png
  docs/assets/khoj_codebase_visualization_0.2.1.png
  docs/assets/khoj_emacs_menu.png
  docs/assets/khoj_obsidian_codebase_visualization_0.2.1.png
  docs/assets/khoj_on_emacs.png
  docs/assets/khoj_on_obsidian_0.2.5.png
  docs/assets/khoj_pwa_android.png
  docs/chat.md
  docs/demos.md
  docs/development.md
  docs/emacs.md
  docs/features.md
  docs/github_integration.md
  docs/index.html
  docs/notion_integration.md
  docs/obsidian.md
  docs/search.md
  docs/setup.md
  docs/windows_install.md
  src/interface/emacs/README.org
Labels: documentation

#356 Fix gpt4all import error in Desktop builds
  Khoj.spec
Labels: fix

#362 Let Offline chat override OpenAI API settings
  src/khoj/processor/conversation/gpt4all/utils.py
  src/khoj/routers/api.py
  src/khoj/routers/helpers.py
  src/khoj/utils/config.py
Labels: upgrade
