Repository khoj-ai/khoj, pull requests merged in 2023-10, with the labels that each got.

#491 Fix Linux Desktop Application
  src/interface/desktop/config.html
  src/interface/desktop/main.js
  src/interface/desktop/package.json
  src/interface/desktop/preload.js
  src/interface/desktop/renderer.js
  src/interface/desktop/yarn.lock
Labels: fix

#487 [Multi-User]: Part 0 - Add support for logging in with Google
  .gitignore
  Dockerfile
  pyproject.toml
  src/app/__init__.py
  src/app/main.py
  src/app/settings.py
  src/app/urls.py
  src/app/wsgi.py
  src/database/__init__.py
  src/database/adapters/__init__.py
  src/database/admin.py
  src/database/apps.py
  src/database/migrations/0001_khojuser.py
  src/database/migrations/0002_googleuser.py
  src/database/migrations/0003_user_khoj_configurations_and_more.py
  src/database/migrations/__init__.py
  src/database/models/__init__.py
  src/khoj/configure.py
  src/khoj/interface/web/index.html
  src/khoj/routers/auth.py
  src/khoj/utils/fs_syncer.py
  src/manage.py
  tests/conftest.py
  tests/test_client.py
Labels: upgrade

#494 Improve Offline Chat Model Experience
  src/khoj/configure.py
  src/khoj/interface/web/config.html
  src/khoj/migrations/migrate_offline_chat_schema.py
  src/khoj/processor/conversation/gpt4all/chat_model.py
  src/khoj/processor/conversation/gpt4all/model_metadata.py
  src/khoj/processor/conversation/gpt4all/utils.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api.py
  src/khoj/routers/helpers.py
  src/khoj/utils/cli.py
  src/khoj/utils/config.py
  src/khoj/utils/rawconfig.py
  tests/conftest.py
  tests/test_gpt4all_chat_actors.py
Labels: upgrade

#499 Push Files to Index from Obsidian, Emacs & Desktop Clients using Multi-Part Forms Method
  pyproject.toml
  src/interface/desktop/main.js
  src/interface/emacs/khoj.el
  src/interface/emacs/tests/khoj-tests.el
  src/interface/obsidian/src/main.ts
  src/interface/obsidian/src/settings.ts
  src/interface/obsidian/src/utils.ts
  src/khoj/configure.py
  src/khoj/main.py
  src/khoj/processor/pdf/pdf_to_jsonl.py
  src/khoj/routers/api.py
  src/khoj/routers/indexer.py
  src/khoj/utils/fs_syncer.py
  src/khoj/utils/helpers.py
  tests/test_client.py
  tests/test_pdf_to_jsonl.py
Labels: maintain

#503 [Multi-User Part 2]: Add login pages and gate access to application behind login wall
  pyproject.toml
  src/database/adapters/__init__.py
  src/khoj/configure.py
  src/khoj/interface/web/base_config.html
  src/khoj/interface/web/config.html
  src/khoj/interface/web/login.html
  src/khoj/main.py
  src/khoj/routers/api.py
  src/khoj/routers/auth.py
  src/khoj/routers/indexer.py
  src/khoj/routers/web_client.py
  tests/conftest.py
  tests/test_client.py
Labels: upgrade

#511 [Multi-User Part 3]: Separate chat sesssions based on authenticated users
  pytest.ini
  src/database/adapters/__init__.py
  src/database/migrations/0007_remove_conversationprocessorconfig_conversation_and_more.py
  src/database/migrations/0008_alter_conversation_conversation_log.py
  src/database/models/__init__.py
  src/khoj/configure.py
  src/khoj/interface/web/config.html
  src/khoj/routers/api.py
  src/khoj/routers/helpers.py
  src/khoj/routers/indexer.py
  src/khoj/routers/web_client.py
  src/khoj/search_type/image_search.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/config.py
  src/khoj/utils/constants.py
  src/khoj/utils/helpers.py
  src/khoj/utils/rawconfig.py
  src/khoj/utils/state.py
  tests/conftest.py
  tests/helpers.py
  tests/test_client.py
  tests/test_gpt4all_chat_director.py
  tests/test_openai_chat_director.py
  tests/test_text_search.py
Labels: upgrade

#513 [Multi-User Part 4]: Authenticate using API Tokens
  src/app/README.md
  src/app/settings.py
  src/app/urls.py
  src/database/adapters/__init__.py
  src/database/migrations/0009_khojapiuser.py
  src/database/models/__init__.py
  src/interface/desktop/assets/icons/favicon-20x20.png
  src/interface/desktop/assets/icons/key.svg
  src/interface/desktop/assets/icons/link.svg
  src/interface/desktop/chat.html
  src/interface/desktop/config.html
  src/interface/desktop/index.html
  src/interface/desktop/main.js
  src/interface/desktop/preload.js
  src/interface/desktop/renderer.js
  src/interface/emacs/khoj.el
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/src/main.ts
  src/interface/obsidian/src/search_modal.ts
  src/interface/obsidian/src/settings.ts
  src/interface/obsidian/src/utils.ts
  src/khoj/configure.py
  src/khoj/interface/web/config.html
  src/khoj/main.py
  src/khoj/processor/conversation/gpt4all/utils.py
  src/khoj/processor/embeddings.py
  src/khoj/routers/api.py
  src/khoj/routers/auth.py
  src/khoj/routers/indexer.py
  src/khoj/routers/web_client.py
  src/khoj/utils/config.py
  src/khoj/utils/helpers.py
  src/khoj/utils/state.py
  tests/conftest.py
  tests/helpers.py
  tests/test_client.py
Labels: upgrade
