Repository khoj-ai/khoj, pull requests merged in 2023-06, with the labels that each got.

#218 Search PDF files with Khoj. Integrate with LangChain
  README.md
  docker-compose.yml
  pyproject.toml
  src/interface/emacs/khoj.el
  src/interface/obsidian/README.md
  src/interface/obsidian/src/search_modal.ts
  src/interface/obsidian/src/settings.ts
  src/interface/obsidian/src/utils.ts
  src/khoj/configure.py
  src/khoj/interface/desktop/file_browser.py
  src/khoj/interface/web/index.html
  src/khoj/processor/conversation/gpt.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/processor/pdf/__init__.py
  src/khoj/processor/pdf/pdf_to_jsonl.py
  src/khoj/routers/api.py
  src/khoj/utils/config.py
  src/khoj/utils/constants.py
  src/khoj/utils/rawconfig.py
  tests/data/pdf/multipage.pdf
  tests/data/pdf/singlepage.pdf
  tests/test_client.py
  tests/test_pdf_to_jsonl.py
Labels: upgrade, coverage

#226 Add a Github plugin which can be used to read from a Github repository
  README.md
  pyproject.toml
  src/khoj/configure.py
  src/khoj/interface/desktop/labelled_text_field.py
  src/khoj/interface/desktop/main_window.py
  src/khoj/interface/web/index.html
  src/khoj/processor/github/__init__.py
  src/khoj/processor/github/github_to_jsonl.py
  src/khoj/processor/jsonl/jsonl_to_jsonl.py
  src/khoj/processor/ledger/beancount_to_jsonl.py
  src/khoj/processor/markdown/markdown_to_jsonl.py
  src/khoj/processor/org_mode/org_to_jsonl.py
  src/khoj/processor/pdf/pdf_to_jsonl.py
  src/khoj/processor/text_to_jsonl.py
  src/khoj/routers/api.py
  src/khoj/utils/config.py
  src/khoj/utils/constants.py
  src/khoj/utils/rawconfig.py
  tests/conftest.py
  tests/test_client.py
  tests/test_conversation_utils.py
  tests/test_text_search.py
Labels: coverage

#236 Update Web Interface with Lantern Theme
  src/khoj/interface/web/assets/icons/chat.svg
  src/khoj/interface/web/assets/icons/github.svg
  src/khoj/interface/web/assets/icons/markdown.svg
  src/khoj/interface/web/assets/icons/org.svg
  src/khoj/interface/web/assets/icons/pdf.svg
  src/khoj/interface/web/assets/khoj.css
  src/khoj/interface/web/assets/pico.min.css
  src/khoj/interface/web/base_config.html
  src/khoj/interface/web/base_data_integration.html
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/config.html
  src/khoj/interface/web/content_type_github_input.html
  src/khoj/interface/web/content_type_input.html
  src/khoj/interface/web/index.html
  src/khoj/interface/web/processor_conversation_input.html
Labels: upgrade, data source

#250 Support multiple Github repositories and support indexing of multiple file types
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/content_type_github_input.html
  src/khoj/interface/web/index.html
  src/khoj/processor/github/github_to_jsonl.py
  src/khoj/processor/markdown/markdown_to_jsonl.py
  src/khoj/processor/org_mode/org_to_jsonl.py
  src/khoj/processor/org_mode/orgnode.py
  src/khoj/routers/api.py
  src/khoj/utils/constants.py
  src/khoj/utils/rawconfig.py
  tests/conftest.py
  tests/test_orgnode.py
Labels: upgrade, coverage, plugin

#232 Search across all Asymmetric Text Content Types in Parallel
  pyproject.toml
  src/interface/emacs/khoj.el
  src/khoj/configure.py
  src/khoj/interface/web/index.html
  src/khoj/processor/conversation/gpt.py
  src/khoj/processor/markdown/markdown_to_jsonl.py
  src/khoj/processor/org_mode/org_to_jsonl.py
  src/khoj/processor/pdf/pdf_to_jsonl.py
  src/khoj/routers/api.py
  src/khoj/search_filter/base_filter.py
  src/khoj/search_filter/date_filter.py
  src/khoj/search_filter/file_filter.py
  src/khoj/search_filter/word_filter.py
  src/khoj/search_type/image_search.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/config.py
  tests/test_client.py
  tests/test_image_search.py
  tests/test_text_search.py
Labels: upgrade

#253 Support indexing Github issues as well as corresponding comments
  config/khoj_docker.yml
  src/khoj/interface/web/index.html
  src/khoj/processor/github/github_to_jsonl.py
  src/khoj/routers/api.py
  tests/conftest.py
  tests/data/markdown/Birthday Gift for Xiu turning 4.markdown
  tests/data/markdown/Hike Mt. Kilimanjaro.markdown
  tests/data/markdown/Meet Arun and Pablo for Lunch.markdown
  tests/data/markdown/Miscellaneous Transactions.markdown
  tests/data/markdown/Namita.markdown
  tests/data/markdown/Patent 6631372.markdown
  tests/data/markdown/Preparing to File Taxes for 2022.markdown
  tests/data/markdown/Sign Wayne Enterprises Offer Letter.markdown
  tests/data/markdown/Submit Resignation Letter to Acme.Inc.markdown
  tests/data/markdown/Visit Seregenti.markdown
  tests/data/markdown/Xi Li.markdown
  tests/data/markdown/copy_what_you_like.markdown
  tests/data/markdown/having_kids.markdown
  tests/data/markdown/how_y_combinator_started.markdown
  tests/data/markdown/jessica_livingston.markdown
  tests/data/markdown/undergraduation.markdown
  tests/data/markdown/what_i_did_this_summer.markdown
  tests/data/markdown/what_i_worked_on.markdown
  tests/data/markdown/why_yc.markdown
Labels: upgrade, plugin
