Repository khoj-ai/khoj, pull requests merged in 2024-01, with the labels that each got.

#604 Fix, Improve Khoj Documentation Layout
  documentation/assets/img/folder_security.svg
  documentation/assets/img/khoj_clients.svg
  documentation/assets/img/khoj_datasources.svg
  documentation/assets/img/lightbulb-plant.svg
  documentation/assets/img/mountains-lake.svg
  documentation/docs/clients/desktop.md
  documentation/docs/clients/emacs.md
  documentation/docs/clients/obsidian.md
  documentation/docs/clients/web.md
  documentation/docs/features/all_features.md
  documentation/docs/features/chat.md
  documentation/docs/features/search.md
  documentation/docs/get-started/overview.md
  documentation/docs/get-started/setup.mdx
  documentation/docusaurus.config.js
  documentation/src/components/HomepageFeatures/index.js
  documentation/src/pages/index.js
  documentation/src/pages/index.module.css
  documentation/src/pages/markdown-page.md
Labels: documentation, maintain

#609 Add option to use HuggingFace's inference endpoint for generating embeddings
  src/interface/desktop/main.js
  src/khoj/configure.py
  src/khoj/database/migrations/0025_searchmodelconfig_embeddings_inference_endpoint_and_more.py
  src/khoj/database/models/__init__.py
  src/khoj/processor/embeddings.py
Labels: upgrade

#605 Remove the 1000 files limit when syncing from Desktop, Obsidian clients
  src/interface/desktop/main.js
  src/interface/desktop/renderer.js
  src/interface/obsidian/src/utils.ts
  src/khoj/routers/indexer.py
  tests/test_client.py
Labels: fix

#607 Short-circuit API rate limiter for unauthenticated users
  pyproject.toml
  src/interface/emacs/khoj.el
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/src/settings.ts
  src/khoj/configure.py
  src/khoj/routers/api.py
  src/khoj/routers/api_beta.py
  src/khoj/routers/api_config.py
  src/khoj/routers/auth.py
  src/khoj/routers/helpers.py
  src/khoj/routers/subscription.py
  tests/conftest.py
  tests/helpers.py
  tests/test_client.py
  tests/test_openai_chat_director.py
Labels: fix

#617 Improve server status check and message in Obsidian client
  src/interface/obsidian/src/main.ts
  src/interface/obsidian/src/settings.ts
  src/interface/obsidian/src/utils.ts
  src/khoj/routers/api.py
Labels: upgrade, plugin

#619 Fix markdownRenderer arg to allow chat responses in Obsidian plugin
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/src/search_modal.ts
Labels: fix, plugin

#601 Add support for a first-party client app to call into Khoj (Part 1)
  pyproject.toml
  src/khoj/app/settings.py
  src/khoj/configure.py
  src/khoj/database/adapters/__init__.py
  src/khoj/database/admin.py
  src/khoj/database/migrations/0025_clientapplication_khojuser_phone_number_and_more.py
  src/khoj/database/migrations/0027_merge_20240118_1324.py
  src/khoj/database/models/__init__.py
  src/khoj/routers/api.py
  src/khoj/routers/helpers.py
  src/khoj/routers/subscription.py
Labels: upgrade

#624 Improve Chat Input Pane Actions. Move to 1 Click Audio Chat on Mobile
  src/interface/desktop/chat.html
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/styles.css
  src/khoj/interface/web/chat.html
Labels: upgrade, plugin

#621 Add support for phone number authentication with Khoj (part 2)
  documentation/docs/clients/whatsapp.md
  pyproject.toml
  src/khoj/database/adapters/__init__.py
  src/khoj/database/admin.py
  src/khoj/database/migrations/0028_khojuser_verified_phone_number.py
  src/khoj/database/models/__init__.py
  src/khoj/interface/web/assets/icons/whatsapp.svg
  src/khoj/interface/web/base_config.html
  src/khoj/interface/web/config.html
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api.py
  src/khoj/routers/api_config.py
  src/khoj/routers/helpers.py
  src/khoj/routers/twilio.py
  src/khoj/routers/web_client.py
Labels: upgrade

#626 Improve subqueries for online search and prompt generation for image
  src/khoj/database/adapters/__init__.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/api.py
  src/khoj/routers/helpers.py
Labels: upgrade

#627 Scrape results from Serper results using Olostep
  pyproject.toml
  src/khoj/interface/web/chat.html
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/openai/utils.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/helpers.py
  tests/test_gpt4all_chat_director.py
  tests/test_helpers.py
  tests/test_openai_chat_director.py
Labels: upgrade
