Repository khoj-ai/khoj, pull requests merged in 2024-12, with the labels that each got.

#993 Do not wrap filepath in Path to fix indexing markdown files on Windows
  src/khoj/processor/content/markdown/markdown_to_entries.py
  src/khoj/processor/content/org_mode/org_to_entries.py
Labels: fix

#992 Make generated assets a non-terminal state
  .github/workflows/run_evals.yml
  src/interface/obsidian/src/chat_view.ts
  src/interface/obsidian/styles.css
  src/interface/web/app/common/chatFunctions.ts
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatMessage/chatMessage.module.css
  src/interface/web/app/components/chatMessage/chatMessage.tsx
  src/khoj/database/admin.py
  src/khoj/database/migrations/0075_migrate_generated_assets_and_validate.py
  src/khoj/database/models/__init__.py
  src/khoj/processor/conversation/anthropic/anthropic_chat.py
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/processor/image/generate.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  tests/test_offline_chat_actors.py
  tests/test_online_chat_director.py
Labels: maintain

#1002 Improve handling of multiple output modes
  src/khoj/processor/conversation/anthropic/anthropic_chat.py
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  tests/test_online_chat_actors.py
Labels: upgrade

#1003 Rename Chat Model Options table to Chat Model as short & readable
  documentation/docs/advanced/litellm.md
  documentation/docs/advanced/lmstudio.md
  documentation/docs/advanced/ollama.mdx
  documentation/docs/advanced/use-openai-proxy.md
  documentation/docs/get-started/setup.mdx
  src/khoj/database/adapters/__init__.py
  src/khoj/database/admin.py
  src/khoj/database/migrations/0077_chatmodel_alter_agent_chat_model_and_more.py
  src/khoj/database/models/__init__.py
  src/khoj/migrations/migrate_server_pg.py
  src/khoj/processor/conversation/anthropic/anthropic_chat.py
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api.py
  src/khoj/routers/api_agents.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/api_model.py
  src/khoj/routers/helpers.py
  src/khoj/utils/initialization.py
  tests/conftest.py
  tests/helpers.py
  tests/test_agents.py
  tests/test_offline_chat_actors.py
  tests/test_offline_chat_director.py
Labels: maintain

#1007 Restart code sandbox on crash in eval github workflow
  .github/workflows/run_evals.yml
Labels: fix

#1014 Improve the agent management UX
  src/interface/web/app/components/agentCard/agentCard.tsx
  src/interface/web/components/ui/tabs.tsx
  src/interface/web/package.json
  src/interface/web/yarn.lock
Labels: upgrade
