Repository khoj-ai/khoj, pull requests merged in 2024-09, with the labels that each got.

#903 Fix URL to web, desktop settings pages on Desktop application
  src/interface/desktop/chat.html
  src/interface/desktop/main.js
  src/interface/desktop/preload.js
Labels: fix, plugin

#889 New Feature: Vision Support for Khoj
  src/interface/desktop/chat.html
  src/interface/desktop/shortcut.html
  src/interface/emacs/khoj.el
  src/interface/obsidian/src/chat_view.ts
  src/interface/web/app/chat/layout.tsx
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatInputArea/chatInputArea.tsx
  src/interface/web/app/components/chatMessage/chatMessage.module.css
  src/interface/web/app/components/chatMessage/chatMessage.tsx
  src/interface/web/app/factchecker/page.tsx
  src/interface/web/app/layout.tsx
  src/interface/web/app/page.tsx
  src/interface/web/app/share/chat/layout.tsx
  src/interface/web/app/share/chat/page.tsx
  src/interface/web/app/share/chat/sharedChat.module.css
  src/interface/web/package.json
  src/interface/web/yarn.lock
  src/khoj/database/adapters/__init__.py
  src/khoj/database/migrations/0056_chatmodeloptions_vision_enabled.py
  src/khoj/database/migrations/0057_merge_20240816_1409.py
  src/khoj/database/migrations/0060_merge_20240905_1828.py
  src/khoj/database/models/__init__.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/utils.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/routers/storage.py
  src/khoj/utils/helpers.py
  tests/test_client.py
  tests/test_offline_chat_director.py
  tests/test_openai_chat_director.py
Labels: upgrade, coverage, plugin, try

#902 Support Google's Gemini model series
  pyproject.toml
  src/khoj/database/adapters/__init__.py
  src/khoj/database/migrations/0061_alter_chatmodeloptions_model_type.py
  src/khoj/database/models/__init__.py
  src/khoj/processor/conversation/google/__init__.py
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/google/utils.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/api.py
  src/khoj/routers/helpers.py
Labels: upgrade, coverage

#912 Support OpenAI's new O1 Model Series
  src/interface/web/app/components/chatMessage/chatMessage.module.css
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/openai/utils.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/helpers.py
Labels: upgrade, coverage

#909 Support using image generation models like Flux via Replicate
  src/khoj/database/migrations/0061_alter_texttoimagemodelconfig_model_type.py
  src/khoj/database/migrations/0062_merge_20240913_0222.py
  src/khoj/database/models/__init__.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/image/generate.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
Labels: upgrade, coverage

#919 Improve Khoj First Run, Docker Setup and Documentation
  docker-compose.yml
  documentation/assets/img/example_search_model_admin_settings.png
  documentation/docs/advanced/admin.md
  documentation/docs/advanced/authentication.md
  documentation/docs/advanced/remote.md
  documentation/docs/get-started/setup.mdx
  documentation/yarn.lock
  pyproject.toml
  src/khoj/main.py
  src/khoj/processor/content/images/image_to_entries.py
  src/khoj/processor/conversation/utils.py
  src/khoj/utils/cli.py
  src/khoj/utils/constants.py
  src/khoj/utils/initialization.py
  tests/test_offline_chat_actors.py
Labels: maintain, docker

#918 Convert the default conversation id to a uuid, plus other fixes
  src/interface/desktop/chat.html
  src/interface/desktop/shortcut.html
  src/interface/obsidian/src/chat_view.ts
  src/interface/web/app/chat/chat.module.css
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/common/chatFunctions.ts
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatInputArea/chatInputArea.tsx
  src/interface/web/app/components/chatMessage/chatMessage.tsx
  src/interface/web/app/components/sidePanel/chatHistorySidePanel.tsx
  src/interface/web/app/share/chat/page.tsx
  src/khoj/database/adapters/__init__.py
  src/khoj/database/migrations/0063_conversation_temp_id.py
  src/khoj/database/migrations/0064_remove_conversation_temp_id_alter_conversation_id.py
  src/khoj/database/models/__init__.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
Labels: upgrade

#923 Only Live Scrolling when at Page Bottom and Add Button to Scroll to Page Bottom on Web App
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatMessage/chatMessage.module.css
  src/interface/web/app/components/chatMessage/chatMessage.tsx
Labels: fix

#926 Reduce tooltip popup delay duration for Create Agent button on Web app
  src/interface/web/app/agents/page.tsx
Labels: fix
