Repository khoj-ai/khoj, pull requests merged in 2024-11, with the labels that each got.

#951 Add Prompt Tracer to Visualize, Analyze and Debug Khoj's Train of Thought
  pyproject.toml
  src/khoj/processor/conversation/anthropic/anthropic_chat.py
  src/khoj/processor/conversation/anthropic/utils.py
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/google/utils.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/openai/utils.py
  src/khoj/processor/conversation/utils.py
  src/khoj/processor/image/generate.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/api.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
Labels: maintain, try

#952 Research Mode: Give Khoj the ability to perform more advanced reasoning
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/common/chatFunctions.ts
  src/interface/web/app/common/colorUtils.ts
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatInputArea/chatInputArea.tsx
  src/interface/web/app/components/chatMessage/chatMessage.tsx
  src/interface/web/app/components/referencePanel/referencePanel.tsx
  src/interface/web/app/components/suggestions/suggestionCard.tsx
  src/interface/web/app/components/suggestions/suggestions.module.css
  src/interface/web/app/components/suggestions/suggestionsData.ts
  src/interface/web/app/factchecker/page.tsx
  src/interface/web/app/page.tsx
  src/interface/web/app/share/chat/page.tsx
  src/interface/web/tailwind.config.ts
  src/khoj/database/adapters/__init__.py
  src/khoj/processor/conversation/anthropic/anthropic_chat.py
  src/khoj/processor/conversation/anthropic/utils.py
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/processor/tools/online_search.py
  src/khoj/processor/tools/run_code.py
  src/khoj/routers/api.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/routers/research.py
  src/khoj/search_filter/date_filter.py
  src/khoj/search_filter/file_filter.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/helpers.py
  src/khoj/utils/yaml.py
  tests/test_text_search.py
Labels: upgrade

#955 Add Script to Evaluate Khoj on Google's FRAMES benchmark
  pyproject.toml
  tests/eval_frames.py
Labels: maintain

#958 Do not CRUD on entries, files & conversations in DB for null user
  src/khoj/configure.py
  src/khoj/database/adapters/__init__.py
  src/khoj/processor/content/docx/docx_to_entries.py
  src/khoj/processor/content/github/github_to_entries.py
  src/khoj/processor/content/images/image_to_entries.py
  src/khoj/processor/content/markdown/markdown_to_entries.py
  src/khoj/processor/content/notion/notion_to_entries.py
  src/khoj/processor/content/org_mode/org_to_entries.py
  src/khoj/processor/content/pdf/pdf_to_entries.py
  src/khoj/processor/content/plaintext/plaintext_to_entries.py
  src/khoj/processor/content/text_to_entries.py
  src/khoj/routers/api.py
  src/khoj/routers/api_content.py
  src/khoj/routers/helpers.py
  src/khoj/routers/notion.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/fs_syncer.py
  tests/conftest.py
  tests/test_client.py
Labels: maintain

#960 Generate and analyze documents with Khoj using the Code sandbox
  src/interface/web/app/common/chatFunctions.ts
  src/interface/web/app/common/iconUtils.tsx
  src/interface/web/app/components/chatMessage/chatMessage.tsx
  src/interface/web/app/components/referencePanel/referencePanel.tsx
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/tools/run_code.py
  src/khoj/routers/api_chat.py
Labels: upgrade

#987 Speed up Docker image builds using multi-stage parallel pipelines
  .dockerignore
  .github/workflows/dockerize.yml
  Dockerfile
  prod.Dockerfile
  src/interface/web/app/agents/layout.tsx
  src/interface/web/app/chat/layout.tsx
  src/interface/web/app/fonts.ts
  src/interface/web/app/globals.css
  src/interface/web/app/layout.tsx
  src/interface/web/app/settings/layout.tsx
  src/interface/web/app/share/chat/layout.tsx
  src/interface/web/package.json
  src/interface/web/tailwind.config.ts
Labels: maintain
