Repository khoj-ai/khoj, pull requests merged in 2024-06, with the labels that each got.

#736 Upgrade Khoj Obsidian: Chat from Side Pane, Stream Intermediate Steps, Copy Message to Clipboard
  src/interface/desktop/chat.html
  src/interface/obsidian/src/chat_modal.ts
  src/interface/obsidian/src/chat_view.ts
  src/interface/obsidian/src/main.ts
  src/interface/obsidian/src/pane_view.ts
  src/interface/obsidian/src/search_modal.ts
  src/interface/obsidian/src/settings.ts
  src/interface/obsidian/src/utils.ts
  src/interface/obsidian/styles.css
  src/khoj/interface/web/chat.html
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
Labels: upgrade, plugin

#735 Repair the issue with file uploads in the Emacs client.
  src/interface/emacs/khoj.el
  src/interface/emacs/tests/khoj-tests.el
Labels: fix

#788 New Feature: Adding File Filtering to Conversations
  src/interface/desktop/config.html
  src/khoj/database/migrations/0044_conversation_file_filters.py
  src/khoj/database/models/__init__.py
  src/khoj/interface/web/chat.html
  src/khoj/routers/api.py
  src/khoj/routers/api_chat.py
  src/khoj/utils/rawconfig.py
Labels: upgrade

#803 Fix: Adding Support for Uploading Multiple Files
  src/khoj/interface/web/chat.html
Labels: fix

#804 UX Improvement: Keyboard Shortcuts for Recent Messages
  src/khoj/database/migrations/0044_conversation_file_filters.py
  src/khoj/interface/web/chat.html
Labels: upgrade

#812 Upgrade Khoj Emacs UX
  src/interface/emacs/khoj.el
  src/interface/emacs/tests/khoj-tests.el
Labels: fix, upgrade, plugin

#801 Support Indexing Docx Files
  pyproject.toml
  src/khoj/database/models/__init__.py
  src/khoj/interface/web/assets/icons/docx.svg
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/content_source_computer_input.html
  src/khoj/processor/content/docx/__init__.py
  src/khoj/processor/content/docx/docx_to_entries.py
  src/khoj/routers/indexer.py
  src/khoj/utils/config.py
  src/khoj/utils/helpers.py
  src/khoj/utils/rawconfig.py
  tests/data/docx/bangalore.docx
  tests/data/docx/iceland.docx
  tests/test_client.py
  tests/test_docx_to_entries.py
Labels: upgrade, coverage

#821 Add support for text to speech in chat responses
  src/khoj/database/adapters/__init__.py
  src/khoj/database/admin.py
  src/khoj/database/migrations/0048_voicemodeloption_uservoicemodelconfig.py
  src/khoj/database/models/__init__.py
  src/khoj/interface/web/assets/icons/speaker.svg
  src/khoj/interface/web/assets/icons/voice.svg
  src/khoj/interface/web/base_config.html
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/config.html
  src/khoj/processor/speech/__init__.py
  src/khoj/processor/speech/text_to_speech.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/api_config.py
  src/khoj/routers/web_client.py
Labels: upgrade

#827 Automatically Find Similar Notes on Emacs in Background
  src/interface/emacs/khoj.el
  src/interface/emacs/tests/khoj-tests.el
Labels: plugin

#825 Use user theme in Obsidian for Khoj plugin styling
  src/interface/obsidian/src/chat_view.ts
  src/interface/obsidian/styles.css
  src/interface/obsidian/yarn.lock
Labels: plugin

#817 Add our first view via Next.js for Agents
  src/interface/web/app/agents/agents.module.css
  src/interface/web/app/agents/agentsLayout.module.css
  src/interface/web/app/agents/layout.tsx
  src/interface/web/app/agents/page.tsx
  src/interface/web/app/chat/chat.module.css
  src/interface/web/app/chat/layout.tsx
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/common/auth.ts
  src/interface/web/app/common/chatFunctions.ts
  src/interface/web/app/components/chatHistory/chatHistory.module.css
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatMessage/chatMessage.module.css
  src/interface/web/app/components/chatMessage/chatMessage.tsx
  src/interface/web/app/components/navMenu/navMenu.module.css
  src/interface/web/app/components/navMenu/navMenu.tsx
  src/interface/web/app/components/referencePanel/referencePanel.module.css
  src/interface/web/app/components/referencePanel/referencePanel.tsx
  src/interface/web/app/components/sidePanel/chatHistorySidePanel.tsx
  src/interface/web/app/components/sidePanel/sidePanel.module.css
  src/interface/web/app/components/suggestions/suggestionCard.tsx
  src/interface/web/app/components/suggestions/suggestions.module.css
  src/khoj/routers/web_client.py
Labels: upgrade

#815 Add OS Level Shortcut Window for Quick Access to Khoj Desktop
  src/interface/desktop/chat.html
  src/interface/desktop/chatutils.js
  src/interface/desktop/main.js
  src/interface/desktop/preload.js
  src/interface/desktop/shortcut.html
Labels: upgrade, help wanted, plugin, try

#836 Allow just one worker to be the background schedule leader
  src/khoj/configure.py
  src/khoj/database/migrations/0050_alter_processlock_name.py
  src/khoj/database/models/__init__.py
  src/khoj/main.py
  src/khoj/routers/api.py
  src/khoj/utils/state.py
Labels: fix
