Repository khoj-ai/khoj, pull requests merged in 2024-07, with the labels that each got.

#823 Support Indexing Images via OCR
  src/interface/desktop/main.js
  src/khoj/interface/web/chat.html
  src/khoj/processor/content/images/__init__.py
  src/khoj/processor/content/images/image_to_entries.py
  src/khoj/routers/indexer.py
  src/khoj/utils/helpers.py
  src/khoj/utils/rawconfig.py
  tests/data/images/nasdaq.jpg
  tests/data/images/testocr.png
  tests/test_image_to_entries.py
Labels: upgrade, coverage

#837 Enable Voice, Keyboard Shortcuts in Khoj Obsidian Plugin
  src/interface/obsidian/src/chat_view.ts
  src/interface/obsidian/src/main.ts
  src/interface/obsidian/src/pane_view.ts
  src/interface/obsidian/src/utils.ts
  src/interface/obsidian/styles.css
Labels: plugin

#842 Add system dependencies required by RapidOCR to fix Khoj Docker image
  Dockerfile
Labels: fix

#851 Fix, Improve Behavior, Styling of Chat View on Web
  src/interface/web/.eslintrc.json
  src/interface/web/.husky/pre-commit
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/components/chatHistory/chatHistory.module.css
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatInputArea/chatInputArea.tsx
  src/interface/web/app/components/chatMessage/chatMessage.module.css
  src/interface/web/app/components/chatMessage/chatMessage.tsx
  src/interface/web/app/components/loading/loading.tsx
  src/interface/web/app/components/navMenu/navMenu.tsx
  src/interface/web/app/components/profileCard/profileCard.module.css
  src/interface/web/app/components/profileCard/profileCard.tsx
  src/interface/web/app/components/referencePanel/referencePanel.tsx
  src/interface/web/app/components/sidePanel/chatHistorySidePanel.tsx
  src/interface/web/app/components/sidePanel/sidePanel.module.css
  src/interface/web/package.json
  src/interface/web/tailwind.config.ts
  src/interface/web/yarn.lock
  src/khoj/routers/api_chat.py
Labels: fix, maintain

#852 Refactor Config API and Settings pages for Reuse and Consistency
  documentation/docs/advanced/litellm.md
  documentation/docs/advanced/lmstudio.md
  documentation/docs/advanced/ollama.md
  documentation/docs/advanced/use-openai-proxy.md
  documentation/docs/clients/desktop.md
  documentation/docs/clients/emacs.md
  documentation/docs/clients/obsidian.md
  documentation/docs/clients/whatsapp.md
  documentation/docs/data-sources/github_integration.md
  documentation/docs/data-sources/notion_integration.md
  src/interface/desktop/main.js
  src/interface/desktop/renderer.js
  src/interface/desktop/search.html
  src/interface/desktop/settings.html
  src/interface/desktop/utils.js
  src/interface/emacs/khoj.el
  src/interface/obsidian/src/utils.ts
  src/interface/web/.eslintrc.json
  src/interface/web/app/components/modelPicker/modelPicker.tsx
  src/interface/web/app/components/navMenu/navMenu.tsx
  src/interface/web/app/components/sidePanel/chatHistorySidePanel.tsx
  src/interface/web/app/factchecker/page.tsx
  src/interface/web/app/share/chat/page.tsx
  src/interface/web/package.json
  src/interface/web/tailwind.config.ts
  src/interface/web/yarn.lock
  src/khoj/configure.py
  src/khoj/interface/web/chat.html
  src/khoj/interface/web/content_source_computer_input.html
  src/khoj/interface/web/content_source_github_input.html
  src/khoj/interface/web/content_source_notion_input.html
  src/khoj/interface/web/public_conversation.html
  src/khoj/interface/web/search.html
  src/khoj/interface/web/settings.html
  src/khoj/interface/web/utils.html
  src/khoj/routers/api.py
  src/khoj/routers/api_config.py
  src/khoj/routers/helpers.py
  src/khoj/routers/indexer.py
  src/khoj/routers/notion.py
  src/khoj/routers/web_client.py
  tests/test_client.py
Labels: maintain

#853 Migrate the PyPI package to project name khoj
  .github/workflows/pypi.yml
  Dockerfile
  README.md
  documentation/docs/advanced/authentication.md
  documentation/docs/contributing/development.mdx
  documentation/docs/get-started/setup.mdx
  pyproject.toml
  src/interface/emacs/khoj.el
  src/khoj/main.py
  src/khoj/routers/auth.py
  src/khoj/utils/cli.py
  src/khoj/utils/helpers.py
Labels: maintain

#860 Upgrade: New Home Screen for Khoj
  src/interface/web/app/agents/page.tsx
  src/interface/web/app/chat/chat.module.css
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/common/chatFunctions.ts
  src/interface/web/app/common/colorUtils.ts
  src/interface/web/app/common/iconUtils.tsx
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatInputArea/chatInputArea.tsx
  src/interface/web/app/components/navMenu/navMenu.tsx
  src/interface/web/app/components/profileCard/profileCard.tsx
  src/interface/web/app/components/sidePanel/chatHistorySidePanel.tsx
  src/interface/web/app/components/sidePanel/sidePanel.module.css
  src/interface/web/app/components/suggestions/suggestionCard.tsx
  src/interface/web/app/components/suggestions/suggestions.module.css
  src/interface/web/app/layout.tsx
  src/interface/web/app/page.module.css
  src/interface/web/app/page.tsx
  src/interface/web/components/ui/tooltip.tsx
  src/interface/web/package-lock.json
  src/interface/web/package.json
  src/interface/web/tailwind.config.ts
  src/interface/web/yarn.lock
  yarn.lock
Labels: upgrade, try

#858 Use Single HTTP API for Robust, Generalizable Chat Streaming
  src/interface/desktop/chat.html
  src/interface/desktop/chatutils.js
  src/interface/desktop/shortcut.html
  src/interface/desktop/utils.js
  src/interface/obsidian/src/chat_view.ts
  src/interface/obsidian/styles.css
  src/khoj/database/adapters/__init__.py
  src/khoj/interface/web/chat.html
  src/khoj/processor/conversation/utils.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/api.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/utils/fs_syncer.py
  tests/test_client.py
  tests/test_offline_chat_director.py
  tests/test_openai_chat_director.py
Labels: upgrade, maintain

#869 Nav Menu Upgrades and Minor UX Improvements
  src/interface/web/app/agents/agents.module.css
  src/interface/web/app/agents/agentsLayout.module.css
  src/interface/web/app/agents/layout.tsx
  src/interface/web/app/agents/page.tsx
  src/interface/web/app/automations/automations.module.css
  src/interface/web/app/automations/automationsLayout.module.css
  src/interface/web/app/automations/layout.tsx
  src/interface/web/app/automations/page.tsx
  src/interface/web/app/chat/chat.module.css
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/common/colorUtils.ts
  src/interface/web/app/common/iconUtils.tsx
  src/interface/web/app/components/chatHistory/chatHistory.module.css
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatInputArea/chatInputArea.tsx
  src/interface/web/app/components/chatMessage/chatMessage.module.css
  src/interface/web/app/components/chatMessage/chatMessage.tsx
  src/interface/web/app/components/logo/khogLogo.tsx
  src/interface/web/app/components/navMenu/navMenu.module.css
  src/interface/web/app/components/navMenu/navMenu.tsx
  src/interface/web/app/components/profileCard/profileCard.tsx
  src/interface/web/app/components/sidePanel/chatHistorySidePanel.tsx
  src/interface/web/app/components/sidePanel/sidePanel.module.css
  src/interface/web/app/globals.css
  src/interface/web/app/page.module.css
  src/interface/web/app/page.tsx
  src/interface/web/app/share/chat/page.tsx
  src/interface/web/app/share/chat/sharedChat.module.css
  src/interface/web/image-loader.ts
  src/interface/web/public/khoj-logo.svg
  src/interface/web/tailwind.config.ts
  src/interface/web/yarn.lock
  src/khoj/routers/api_agents.py
Labels: upgrade
