Repository khoj-ai/khoj, pull requests merged in 2024-04, with the labels that each got.

#683 Extract More Dates from entries to improve Date Filter
  src/khoj/search_filter/date_filter.py
  tests/test_date_filter.py
Labels: upgrade

#679 Add a websocket for streaming from the chat UI
  pyproject.toml
  src/khoj/interface/web/chat.html
  src/khoj/routers/api.py
  src/khoj/routers/api_chat.py
Labels: upgrade

#645 Update Text Chunking Strategy to Improve Search Context
  src/khoj/processor/content/markdown/markdown_to_entries.py
  src/khoj/processor/content/org_mode/org_to_entries.py
  src/khoj/processor/content/org_mode/orgnode.py
  src/khoj/processor/content/pdf/pdf_to_entries.py
  src/khoj/processor/content/plaintext/plaintext_to_entries.py
  src/khoj/processor/content/text_to_entries.py
  src/khoj/routers/api_chat.py
  tests/test_client.py
  tests/test_markdown_to_entries.py
  tests/test_multiple_users.py
  tests/test_openai_chat_actors.py
  tests/test_org_to_entries.py
  tests/test_pdf_to_entries.py
  tests/test_plaintext_to_entries.py
  tests/test_text_search.py
Labels: fix, upgrade

#692 Index more text file types from Desktop, Github
  pyproject.toml
  src/interface/desktop/main.js
  src/interface/desktop/package.json
  src/interface/desktop/yarn.lock
  src/khoj/processor/content/github/github_to_entries.py
  src/khoj/processor/content/plaintext/plaintext_to_entries.py
  src/khoj/processor/content/text_to_entries.py
  src/khoj/routers/indexer.py
  src/khoj/utils/fs_syncer.py
  src/khoj/utils/helpers.py
  tests/test_client.py
  tests/test_plaintext_to_entries.py
Labels: fix, coverage, maintain

#703 Improve Chat Page Load Perf, Offline Chat Perf and Miscellaneous Fixes
  documentation/docs/get-started/setup.mdx
  pyproject.toml
  src/interface/desktop/chat.html
  src/interface/obsidian/src/chat_modal.ts
  src/khoj/configure.py
  src/khoj/database/adapters/__init__.py
  src/khoj/database/admin.py
  src/khoj/database/management/__init__.py
  src/khoj/database/management/commands/__init__.py
  src/khoj/database/management/commands/convert_images_png_to_webp.py
  src/khoj/database/migrations/0035_convert_png_to_webp.py
  src/khoj/interface/web/chat.html
  src/khoj/processor/content/github/github_to_entries.py
  src/khoj/processor/content/notion/notion_to_entries.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/offline/utils.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/routers/storage.py
  src/khoj/utils/config.py
  src/khoj/utils/helpers.py
Labels: fix, maintain

#724 Support Llama 3 and Improve Offline Chat Actors
  pyproject.toml
  src/khoj/processor/conversation/offline/utils.py
  src/khoj/processor/conversation/prompts.py
  tests/test_offline_chat_actors.py
Labels: maintain
