Repository khoj-ai/khoj, pull requests merged in 2024-10, with the labels that each got.

#929 Make Online Search Location Aware
  src/interface/desktop/chat.html
  src/interface/desktop/shortcut.html
  src/interface/obsidian/src/chat_view.ts
  src/interface/web/app/automations/page.tsx
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/common/utils.ts
  src/interface/web/app/share/chat/page.tsx
  src/khoj/processor/conversation/anthropic/anthropic_chat.py
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/utils/helpers.py
  src/khoj/utils/rawconfig.py
Labels: upgrade

#928 Add support for personal agents with custom knowledge bases
  src/interface/web/app/agents/page.tsx
  src/interface/web/app/common/auth.ts
  src/interface/web/app/common/colorUtils.ts
  src/interface/web/app/common/iconUtils.tsx
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatInputArea/chatInputArea.tsx
  src/interface/web/app/components/profileCard/profileCard.tsx
  src/interface/web/app/components/shareLink/shareLink.tsx
  src/interface/web/app/components/sidePanel/chatHistorySidePanel.tsx
  src/interface/web/app/page.tsx
  src/interface/web/app/settings/page.tsx
  src/khoj/database/adapters/__init__.py
  src/khoj/database/migrations/0065_remove_agent_avatar_remove_agent_public_and_more.py
  src/khoj/database/migrations/0066_remove_agent_tools_agent_input_tools_and_more.py
  src/khoj/database/migrations/0067_alter_agent_style_icon.py
  src/khoj/database/models/__init__.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/routers/api.py
  src/khoj/routers/api_agents.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/helpers.py
Labels: upgrade

#916 Include agent personality through subtasks and support custom agents
  src/interface/web/app/agents/page.tsx
  src/interface/web/app/common/auth.ts
  src/interface/web/app/common/colorUtils.ts
  src/interface/web/app/common/iconUtils.tsx
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatInputArea/chatInputArea.tsx
  src/interface/web/app/components/profileCard/profileCard.tsx
  src/interface/web/app/components/shareLink/shareLink.tsx
  src/interface/web/app/components/sidePanel/chatHistorySidePanel.tsx
  src/interface/web/app/page.tsx
  src/interface/web/app/settings/page.tsx
  src/khoj/database/adapters/__init__.py
  src/khoj/database/migrations/0065_remove_agent_avatar_remove_agent_public_and_more.py
  src/khoj/database/migrations/0066_remove_agent_tools_agent_input_tools_and_more.py
  src/khoj/database/migrations/0067_alter_agent_style_icon.py
  src/khoj/database/models/__init__.py
  src/khoj/processor/conversation/anthropic/anthropic_chat.py
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/image/generate.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/api.py
  src/khoj/routers/api_agents.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/helpers.py
Labels: upgrade

#936 Make Chat and Online Search Resilient and Faster
  src/khoj/database/adapters/__init__.py
  src/khoj/database/admin.py
  src/khoj/database/migrations/0069_webscraper_serverchatsettings_web_scraper.py
  src/khoj/database/models/__init__.py
  src/khoj/processor/embeddings.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/search_type/text_search.py
  src/khoj/utils/helpers.py
Labels: maintain

#940 Generate dynamic diagrams (via Excalidraw)
  src/interface/desktop/chat.html
  src/interface/desktop/chatutils.js
  src/interface/obsidian/src/chat_view.ts
  src/interface/web/app/chat/chat.module.css
  src/interface/web/app/chat/layout.tsx
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/common/chatFunctions.ts
  src/interface/web/app/common/iconUtils.tsx
  src/interface/web/app/components/chatHistory/chatHistory.module.css
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatMessage/chatMessage.tsx
  src/interface/web/app/components/excalidraw/excalidraw.tsx
  src/interface/web/app/components/excalidraw/excalidrawWrapper.tsx
  src/interface/web/app/share/chat/layout.tsx
  src/interface/web/app/share/chat/page.tsx
  src/interface/web/app/share/chat/sharedChat.module.css
  src/interface/web/package.json
  src/interface/web/yarn.lock
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/routers/web_client.py
  src/khoj/utils/helpers.py
Labels: upgrade, try
