Repository khoj-ai/khoj, pull requests merged in 2025-04, with the labels that each got.

#1148 Improve Gemini Response Reliability
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/google/utils.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/routers/helpers.py
Labels: maintain

#1150 Improve response quality with Gemini. Improve evaluation harness
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/workflows/run_evals.yml
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/google/utils.py
  src/khoj/processor/conversation/prompts.py
  src/khoj/processor/conversation/utils.py
  src/khoj/processor/tools/online_search.py
  src/khoj/routers/research.py
  src/khoj/utils/helpers.py
  tests/evals/eval.py
Labels: upgrade

#1157 Fix and Improve Chat sidebar and component setup on Web App
  src/interface/web/app/agents/layout.tsx
  src/interface/web/app/automations/layout.tsx
  src/interface/web/app/chat/layout.tsx
  src/interface/web/app/common/modelSelector.tsx
  src/interface/web/app/components/chatHistory/chatHistory.tsx
  src/interface/web/app/components/chatSidebar/chatSidebar.tsx
  src/interface/web/app/layout.tsx
  src/interface/web/app/search/layout.tsx
  src/interface/web/app/settings/layout.tsx
  src/interface/web/app/settings/page.tsx
  src/interface/web/app/share/chat/layout.tsx
Labels: fix

#1158 Add FAQ section to Readme and Troubleshooting Tips to setup GCP Vertex
  README.md
  documentation/docs/advanced/gcp-vertex.md
Labels: documentation

#1151 Allow Model switching based on User Tier
  .github/workflows/pypi.yml
  src/interface/web/app/chat/page.tsx
  src/interface/web/app/common/auth.ts
  src/interface/web/app/common/modelSelector.tsx
  src/interface/web/app/components/agentCard/agentCard.tsx
  src/interface/web/app/components/chatSidebar/chatSidebar.tsx
  src/interface/web/app/settings/page.tsx
  src/interface/web/package.json
  src/khoj/database/adapters/__init__.py
  src/khoj/database/migrations/0089_chatmodel_price_tier_and_more.py
  src/khoj/database/models/__init__.py
  src/khoj/routers/api_agents.py
  src/khoj/routers/api_model.py
  src/khoj/routers/helpers.py
Labels: upgrade

#1167 Simplify AI Chat Response Streaming
  src/khoj/database/adapters/__init__.py
  src/khoj/processor/conversation/anthropic/anthropic_chat.py
  src/khoj/processor/conversation/anthropic/utils.py
  src/khoj/processor/conversation/google/gemini_chat.py
  src/khoj/processor/conversation/google/utils.py
  src/khoj/processor/conversation/offline/chat_model.py
  src/khoj/processor/conversation/openai/gpt.py
  src/khoj/processor/conversation/openai/utils.py
  src/khoj/processor/conversation/utils.py
  src/khoj/routers/api_chat.py
  src/khoj/routers/helpers.py
  src/khoj/utils/helpers.py
Labels: upgrade
